apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: video-chat-staging

namespace: staging

resources:
- ../base

namePrefix: staging-

patchesStrategicMerge:
- staging-patches.yaml

configMapGenerator:
- name: video-chat-config
  behavior: merge
  literals:
  - NODE_ENV=staging
  - FRONTEND_URL=https://staging.video-chat.example.com
  - LOG_LEVEL=debug

secretGenerator:
- name: video-chat-secrets
  behavior: merge
  literals:
  - JWT_SECRET=staging-jwt-secret-change-in-production

replicas:
- name: video-chat-frontend
  count: 2
- name: video-chat-backend
  count: 2

images:
- name: ghcr.io/YOUR_USERNAME/decentralized-video-app-frontend
  newTag: ${FRONTEND_IMAGE_TAG}
- name: ghcr.io/YOUR_USERNAME/decentralized-video-app-backend
  newTag: ${BACKEND_IMAGE_TAG}