apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-chat-frontend
  namespace: staging
spec:
  template:
    spec:
      containers:
      - name: frontend
        resources:
          requests:
            memory: "32Mi"
            cpu: "25m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-chat-backend
  namespace: staging
spec:
  template:
    spec:
      containers:
      - name: backend
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "250m"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: video-chat-ingress
  namespace: staging
spec:
  rules:
  - host: staging.video-chat.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: video-chat-frontend-service
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: video-chat-backend-service
            port:
              number: 5001
      - path: /socket.io
        pathType: Prefix
        backend:
          service:
            name: video-chat-backend-service
            port:
              number: 5001