name: Continuous Integration

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    
    - name: Install Dependencies
      run: npm ci
    
    - name: Lint
      run: npm run lint
    
    - name: Unit Tests
      run: npm run test:coverage
    
    - name: E2E Tests
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
      run: npm run test:e2e
    
    - name: Performance Audit
      run: npm run performance:audit
    
    - name: Security Scan
      run: npm run security:scan
    
    - name: Upload Coverage
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage/coverage-final.json