name: Dependency Updates

on:
  schedule:
    - cron: '0 6 * * 1'  # Every Monday at 6 AM UTC
  workflow_dispatch:

jobs:
  dependency-audit:
    name: Dependency Security Audit
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run npm audit
      run: npm audit --audit-level=high --production

    - name: Run Snyk security scan
      uses: snyk/actions/node@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --severity-threshold=high --dev

    - name: Check for vulnerable dependencies
      run: |
        npm audit --audit-level=moderate --json > audit-results.json
        if [ $(jq '.metadata.vulnerabilities.total' audit-results.json) -gt 0 ]; then
          echo "Security vulnerabilities found!"
          jq '.vulnerabilities' audit-results.json
          exit 1
        fi

  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    needs: dependency-audit
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Update dependencies
      run: |
        npx npm-check-updates -u --target minor
        npm install
        npm audit fix --force

    - name: Run tests after updates
      run: |
        npm run test:unit
        npm run lint

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update dependencies'
        title: 'Automated Dependency Updates'
        body: |
          ## 🔄 Automated Dependency Updates
          
          This PR contains automated dependency updates:
          
          - Minor version updates for all dependencies
          - Security fixes from npm audit
          - All tests passing
          
          Please review the changes before merging.
        branch: dependency-updates
        delete-branch: true

  container-security:
    name: Container Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Build Docker images for scanning
      run: |
        docker build -f docker/Dockerfile.frontend -t frontend-scan .
        docker build -f docker/Dockerfile.backend -t backend-scan .

    - name: Scan frontend image
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'frontend-scan'
        format: 'sarif'
        output: 'frontend-trivy-results.sarif'

    - name: Scan backend image
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'backend-scan'
        format: 'sarif'
        output: 'backend-trivy-results.sarif'

    - name: Upload Trivy scan results
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: '.'